token_type_decl(TOKEN_UNKNOWN)
token_type_decl(TOKEN_IDENTIFIER)

token_type_decl(TOKEN_COMMENT)
token_type_decl(TOKEN_WHITESPACE)

token_type_decl(TOKEN_PARENTHETICAL_OPEN)
token_type_decl(TOKEN_PARENTHETICAL_CLOSE)
token_type_decl(TOKEN_BRACE_OPEN)
token_type_decl(TOKEN_BRACE_CLOSE)

token_type_decl(TOKEN_FEED_RIGHT)
token_type_decl(TOKEN_FEED_LEFT)

token_type_decl(TOKEN_TEMPLATE_DIRECTIVE)
token_type_decl(TOKEN_TEMPLATE_TYPE_IDENTIFIER)
token_type_decl(TOKEN_TEMPLATE_TYPE)
token_type_decl(TOKEN_TEMPLATE_VARIABLE)

token_type_decl(TOKEN_TEMPLATE_ARGUMENT_DECL)
token_type_decl(TOKEN_TEMPLATE_NAME)
token_type_decl(TOKEN_TEMPLATE_GEN_NAME)
token_type_decl(TOKEN_TEMPLATE_STATEMENT_NAME)

//TOKEN_END_OF_FILE,

